export const COMPANY_DATA = {
  cls: {
    name: 'Canada Lumper Services (CLS)',
    status: 'active',
    statusLabel: 'Active — Current Employer',
    phone: '647-537-0625',
    email: 'julian@canlumpers.com',
    address: '2233 Argentia Rd, Mississauga, ON L5N 2X7',
    availability: '🌙 Overnight',
    jobsDone: 4,
    avgPay: '$110.22',
    reliability: '100%',
    notes: 'Current employer. Agreement signed Apr 1 2026. Pay via app weekly.',
    activity: [
      { icon: 'inventory_2', color: 'text-orange-400', label: 'Container Job — Fresh Taste Produce', sub: 'GINGER · 1584 pcs · $187.53', date: 'Apr 11' },
      { icon: 'inventory_2', color: 'text-teal-400',   label: 'Container Job — TAS Refrigerated',   sub: 'FSCU5734460 · 1800 pcs · $75.00', date: 'Apr 6' },
      { icon: 'inventory_2', color: 'text-teal-400',   label: 'Container Job — TAS Refrigerated',   sub: 'KKFU6751964 · Half 3 Ways · $38.33', date: 'Apr 6' },
      { icon: 'inventory_2', color: 'text-orange-400', label: 'Container Job — TAS Refrigerated',   sub: 'ZCLU9930419 · 318 pcs · $140.00', date: 'Apr 1' },
      { icon: 'description', color: 'text-blue-400',   label: 'Agreement Signed', sub: 'Subcontractor Agreement · App setup complete', date: 'Apr 1' },
    ],
  },
  greatnorth: {
    name: 'Great North Lumper Services',
    status: 'sep',
    statusLabel: 'September 2026 Follow-up',
    phone: '416-419-5222',
    email: 'info@greatnorthlumpers.com',
    address: '6033 Shawson Dr, Unit 25, Mississauga, ON L5T 1H8',
    availability: '☀️ Morning/Afternoon',
    jobsDone: 0,
    avgPay: '—',
    reliability: '—',
    notes: 'Replied to text — mornings only. Weekends go to FT staff first. Follow up Sep for FT role.',
    activity: [
      { icon: 'message',      color: 'text-green-400', label: 'They Replied', sub: 'Morning/Afternoon only. Weekends = FT staff OT.', date: 'Apr 13' },
      { icon: 'phone_iphone', color: 'text-blue-400',  label: 'Text Sent',    sub: 'Intro message sent 12:50AM', date: 'Apr 13' },
    ],
  },
  trojan: {
    name: 'Trojan Lumping Services',
    status: 'sent',
    statusLabel: 'Texted — Awaiting Reply',
    phone: '416-716-1404',
    email: 'stevenjames@trojanlumping.com',
    address: '7035 Ordan Drive, Mississauga, ON L5T 1R1',
    availability: '🌙 Overnight + 📅 Weekend',
    jobsDone: 0,
    avgPay: '—',
    reliability: '—',
    notes: 'Brampton/Mississauga. Overnight + weekends. Owner: Steven James Kucher. High priority.',
    activity: [
      { icon: 'phone_iphone', color: 'text-blue-400', label: 'Text Sent', sub: 'Intro message sent', date: 'Apr 13' },
    ],
  },
  containerguyz: {
    name: 'Container Guyz',
    status: 'sent',
    statusLabel: 'Texted — Awaiting Reply',
    phone: '647-234-4214',
    email: 'containerguyz@gmail.com',
    address: '462 Hyacinthe Blvd, Mississauga, ON',
    availability: '🌙 Overnight',
    jobsDone: 0,
    avgPay: '—',
    reliability: '—',
    notes: 'Fastest growing lumper company in Mississauga. Apply form at containerguyz.ca.',
    activity: [
      { icon: 'phone_iphone', color: 'text-blue-400', label: 'Text Sent', sub: 'Intro message sent', date: 'Apr 13' },
    ],
  },
  bcs: {
    name: 'Brothers Container Service (BCS)',
    status: 'sent',
    statusLabel: 'Texted — Awaiting Reply',
    phone: '416-908-7581',
    email: 'containerservices.ca/contact-bcs',
    address: 'GTA & Southern Ontario',
    availability: '🌙 24/7 + 📅 Weekend',
    jobsDone: 0,
    avgPay: '—',
    reliability: '—',
    notes: '24/7 service since 2007. Sales: Wojtek Oles 416-908-7581. Ops: Norbert Kolcz 905-399-1354.',
    activity: [
      { icon: 'phone_iphone', color: 'text-blue-400', label: 'Text Sent', sub: 'Intro message sent', date: 'Apr 13' },
    ],
  },
};

export const PIPE_COMPANIES = [
  { key: 'cls',           dot: 'dot-active', name: 'Canada Lumper Services (CLS)',       contact: 'julian@canlumpers.com · 647-537-0625',           tags: [['tag-orange','🌙 Overnight'],['tag-green','Active ✓']],                       note: 'Current employer. Nights working.',                              filter: 'active overnight' },
  { key: 'greatnorth',   dot: 'dot-sep',    name: 'Great North Lumper Services',         contact: '416-419-5222',                                   tags: [['tag-yellow','☀️ Morning/Afternoon'],['tag-purple','📌 Sep 2026']],            note: 'Replied — mornings only. Weekends go to FT staff. Follow up Sep for FT role.', filter: 'september weekend' },
  { key: 'trojan',       dot: 'dot-sent',   name: 'Trojan Lumping Services',             contact: '416-716-1404 · stevenjames@trojanlumping.com',   tags: [['tag-orange','🌙 Overnight'],['tag-blue','📅 Weekend'],['tag-blue','Texted']], note: '',                                                               filter: 'overnight weekend' },
  { key: 'containerguyz',dot: 'dot-sent',   name: 'Container Guyz',                      contact: '647-234-4214 · containerguyz@gmail.com',         tags: [['tag-orange','🌙 Overnight'],['tag-blue','Texted']],                          note: 'Mississauga — fastest growing lumper co.',                       filter: 'overnight weekend' },
  { key: 'bcs',          dot: 'dot-sent',   name: 'Brothers Container Service (BCS)',    contact: '416-908-7581 · 905-399-1354',                    tags: [['tag-orange','🌙 24/7'],['tag-blue','📅 Weekend'],['tag-blue','Texted']],      note: '',                                                               filter: 'overnight weekend' },
  { key: null,           dot: 'dot-sent',   name: 'QuickCan Lumping Service',            contact: '647-909-3320',                                   tags: [['tag-orange','🌙 Overnight'],['tag-blue','Texted']],                          note: '',                                                               filter: 'overnight' },
  { key: null,           dot: 'dot-none',   name: 'Container Solutions Inc.',            contact: '1-888-289-5155 · info@containersolutions.com',   tags: [['tag-orange','🌙 24hr'],['tag-muted','Not Contacted']],                       note: '',                                                               filter: 'overnight weekend' },
  { key: null,           dot: 'dot-none',   name: 'National Lumpers',                    contact: 'jobs@nationallumpers.com',                       tags: [['tag-orange','🌙 Flexible'],['tag-muted','Email Pending']],                   note: '',                                                               filter: 'overnight weekend' },
  { key: null,           dot: 'dot-none',   name: 'Direct Lumper Service Inc.',          contact: '7270 Torbram Rd, Mississauga',                   tags: [['tag-orange','🌙 Full Time GTA'],['tag-muted','Not Contacted']],              note: '',                                                               filter: 'overnight weekend' },
  { key: null,           dot: 'dot-none',   name: 'Bal — Independent Dispatcher',        contact: '647-707-5725 (text only)',                       tags: [['tag-orange','🌙 On-Demand'],['tag-muted','Not Contacted']],                  note: '',                                                               filter: 'overnight' },
  { key: null,           dot: 'dot-none',   name: 'Eclipse Advantage / ECM',             contact: '905-793-7748 ext.1 · eclipseadvantage.ca',       tags: [['tag-orange','🌙 Night Shift'],['tag-muted','Not Contacted']],                note: 'Active night shift postings Mar 2026. $20–28/hr.',               filter: 'overnight' },
  { key: null,           dot: 'dot-sep',    name: 'LumpCo',                              contact: 'lumpco.ca/contact',                              tags: [['tag-yellow','☀️ Morning/Afternoon'],['tag-purple','📌 Sep 2026']],            note: '',                                                               filter: 'september weekend' },
];
